name: Code Quality

on:
  push:
    branches: [main, master, develop, "feature/**", "release/**", "hotfix/**"]
  pull_request:
    branches: [main, master, develop]
permissions:
  contents: read
  checks: write

jobs:
  biome-check:
    name: Biome Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        # The action will automatically detect the version from your package.json
      - name: Run Biome with auto‑fix
        run: npx biome check --apply .

      - name: Run Biome CI Check
        run: biome ci .
        # The 'ci' command combines linting, formatting checks in one command
